force-app/main/default/objects/CryptoCurrency__c/CryptoCurrency__c.object-meta.xml
<CustomObject>
    <label>CryptoCurrency</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CryptoCurrencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CryptoCurrency__c/fields/Symbol__c.field-meta.xml
<CustomField>
    <fullName>Symbol__c</fullName>
    <label>Symbol</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CryptoCurrenciesSelector.cls
public with sharing class CryptoCurrenciesSelector extends fflib_SObjectSelector {
    public Schema.SObjectType getSObjectType() {
        return CryptoCurrency__c.getSObjectType();
    }

    public List<Schema.SObjectField> getSObjectFieldSetList() {
        return new List<Schema.SObjectField> {
            CryptoCurrency__c.Symbol__c,
            CryptoCurrency__c.Name,
            CryptoCurrency__c.Id
        };
    }

    public List<CryptoCurrency__c> selectById(Set<Id> idSet) {
        return (List<CryptoCurrency__c>) selectSObjectsById(idSet);
    } 

    public List<CryptoCurrency__c> selectBySymbol(Set<String> symbolSet) {
        return (List<CryptoCurrency__c>) Database.query(
                newQueryFactory()
                    .setCondition('Symbol__c IN :symbolSet')
                    .toSOQL()
            );
    }

}